---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %} state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana


- name: Make sure Kibana home dir has right permissions
  file:
    path: /usr/share/kibana
    state: directory
    owner: kibana
    group: kibana
    recurse: yes
