---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana{% if kibana_version is defined and kibana_version != ""  %}-{{ kibana_version }}{% endif %} state=present


- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/etc/kibana/kibana.yml"
    owner: kibana
    group: kibana
    mode: 0644
    force: yes
  notify: restart kibana

- name: Install X-pack
  shell: "/usr/share/kibana/bin/kibana-plugin install x-pack"
  when: kibana_enable_xpack is defined and kibana_enable_xpack == true

- name: Make sure Kibana home dir has right permissions
  file:
    path: /usr/share/kibana
    state: directory
    owner: kibana
    group: kibana

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
    state: started
    enabled: yes
